### ISSUE TITLE
REST API Endpoints and Functionality

### ISSUE THREAD

**Issue by gaurangsadekar** [gaurangsadekar/pricetell#1]
Endpoints
### Client Endpoints
- [x] User Register - I guess Login would be handled by Facebook
- [x] User tracks new product: Handles case of product already being in the DB and user already tracking the product - Pushed Changes
- [x] User wants to delete a product he is tracking.
- [x] Get all products for a user to show on the front end.
### Crawler Endpoints
- [x] Price of a product changes, update DB and decide whether to notify or not.
- [x] List of all unique URLs for the crawler 

Functionality:
- [x] Notify user if price changes - Email, Push Notif, etc.

**Comment by prakhar1989** [comment]
The endpoints listed above for the clients. I would suggest breaking this into two parts

### Client API
- user create
- product create
- product delete
- product list

| route | params | output |
| --- | --- | --- |
| `/product/delete` | `user_id`, `product_id` | None |

### Crawler API
- list of all **unique** urls to cross
- update price of a product

| route | params | output |
| --- | --- | --- |
| `/allproducts` | None | array of products |

I would also suggest adding routes / params info here itself (don't bother creating a new document).

**Comment by gaurangsadekar** [comment]
I'll address your comments 1 by 1:
- the product/delete route you described is implemented currently as a DELETE request at the endpoint user/:fb_id/product and takes the site and product_id as body parameters. Is that cool or should I change it? 
- Once I'm done implementing, I'll add the routes/ params info here itself.
- One thing I need to check is whether we are keeping a bunch of products in the DB that no users are tracking. Currently, deleting a product from a tracked list just removes it from the userProduct mapping. We need to figure out a way to remove that product from the products table as well. There are 2 ways to do this:
  -- When a user deletes a product, check if that product is still being tracked by any other user. If not, delete it from the product table as well.
  -- Schedule a check on the product table before crawling the URLs for each product.

Suggestions?

**Comment by prakhar1989** [comment]
> implemented currently as a DELETE request

This is right way to go about it. Don't change it.

> When a user deletes a product, check if that product is still being tracked by any other user. If not, delete it from the product table as well.

This makes sense.  You can write something like 

``` SQL
DELETE FROM product
WHERE 
    (SELECT count(*) FROM userProducts WHERE pid = pid) = 0 
AND pid = pid;
```

Write this query **after** you've deleted the entry from `userProduct` table.

**Comment by gaurangsadekar** [comment]
Oh, one other thing: When the new price is higher than the old price, what action do we take?

**Comment by prakhar1989** [comment]
Add the entry in the productHistory table.

**Comment by gaurangsadekar** [comment]
All routes are exposed as domain:port/api/

#### Client Routes

| Route | Params | Request Method | Output |
| --- | --- | --- | --- |
| `/register` | `fbid, email` | `POST` | `{success: true, fbid: }` if request is successful |
| `/user/:fbid/products` | `fbid (in URL)` | `GET` | JSON Array of all tracked products `{products: [{site:, url:, title:,image_url:, price:}]}` |
| `/user/:fbid/product` | `fbid (in URL), title, URL, site, price, product_id, image_url` | `POST` | Adds a product to a user's list, sends `{message: String}`(Check if not null) |
| `/user/:fbid/product` | `fbid(in URL), site, product_id` | `DELETE` | Removes a product from the user's list and checks if that product is being tracked by any other users. Sends `{message: "Product Removed"}` on success |

#### Crawler Routes

| Route | Params | Request Method | Output |
| --- | --- | --- | --- |
| `/crawl/allproducts` |  | `GET` | Returns an array of products to crawl. `{product: {site:, product_id:, url:}}` |
| `/crawl/newprice` | `site, product_id, new_price` | `POST` | Updates the product price, sends notification to client |

What kind of notification are we implementing? Email only right?

**Comment by prakhar1989** [comment]
Good stuff! Looks the microservice course is paying off :dancers: Can you deploy this somewhere so that I can get started on testing this?
